export const SET_PRODUCT_ELEMENT_FORM = "SET_PRODUCT_ELEMENT_FORM";
export const SET_PRODUCT_FORM = "SET_PRODUCT_FORM";
export const SET_PRODUCTION_FORM = "SET_PRODUCTION_FORM";
export const SET_LEADER_PRODUCTION = "SET_LEADER_PRODUCTION";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const SET_ISPRODUCTION_EDITABLE = "SET_ISPRODUCTION_EDITABLE";
